### ISSUE TITLE
Publish Game

### ISSUE THREAD

**Issue by bluelotus03** [bluelotus03/Hackcoming-Game-2021#2]
- [x] Come up with some domain names 
- [x] Find one that's available on GoDaddy
- [x] Figure out how to publish the game from Replit to a website version (if possible) - or display the screen preview size of replit to play on screen

**Comment by bluelotus03** [comment]
For names, maybe something like "Save the Holidays" or something related to Santa, North Pole, Winter Wonderland, etc. Interested to hear your ideas (:

**Comment by elreydetoda** [comment]
- [x] add border and center canvas

**Comment by elreydetoda** [comment]
closed by:
- https://github.com/bluelotus03/Hackcoming-Game-2021/commit/128c564adc9442a3755c9fdebd84a5a0d77aeb21
- https://github.com/bluelotus03/Hackcoming-Game-2021/commit/cac5431b97cefb879d28862a96289ece7f2d0a80
